language: c

- os: linux
name: "ARM GCC"
env:
  - "C_COMPILER=arm-none-eabi-gcc"
  - "CXX_COMPILER=arm-none-eabi-gcc"
  - "SIZE=arm-none-eabi-size"
  - "OBJCOPY=arm-none-eabi-objcopy"
  - "LINKER=arm-none-eabi-ld"
  - "LLD=arm-none-eabi-ld.bfd"

script: 
  - sudo apt-get install build-essential 
  - sudo apt install -y make gcc
  - gcc --version
  - sudo apt-get install gcc-arm-none-eabi
  - gcc -I./include -I./system/include/stm32f4-hal -I./system/include/cmsis -I./system/include/diag -o main ./src/main.c